name: CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CI/CD pipeline started
        run: echo "CI/CD pipeline is ready for development"